apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "general-app-chart.fullname" . }}
  labels:
    {{- include "general-app-chart.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.container.envs }}
  {{ $key | upper }}: {{ $value | quote}}
{{- end }}
