{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "general-app-chart.fullname" . }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreRef }}
  target:
    name: {{ template "general-app-chart.fullname" . }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.originSecretKey }}
---
{{- end }}
{{- if .Values.externalSecret.asFiles.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "general-app-chart.fullname" . }}-as-files
spec:
  refreshInterval: {{ .Values.externalSecret.asFiles.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.asFiles.secretStoreRef }}
  target:
    name: {{ template "general-app-chart.fullname" . }}-as-files
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{- range .Values.externalSecret.asFiles.originSecrets }}
        {{ .fileName }}: |
          {{ printf "{{ index . \"%s\" }}" .key }}
        {{- end }}
  data:
  {{- range .Values.externalSecret.asFiles.originSecrets }}
  - secretKey: {{ .key | quote }}
    remoteRef:
      key: {{ .key | quote }}
  {{- end }}
{{- end }}
