{{- if .Values.rbac.create -}}
apiVersion: {{ include "general-app-chart.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ template "general-app-chart.fullname" . }}
  labels:
    {{- include "general-app-chart.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "general-app-chart.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "general-app-chart.serviceAccountName" . }}
  namespace: {{ template "general-app-chart.namespace" . }}
{{- end }}
