{{- if .Values.vpa.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "general-app-chart.fullname" . }}
  labels:
    {{- include "general-app-chart.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       {{ include "general-app-chart.fullname" . }}
  updatePolicy:
    updateMode: "{{ .Values.vpa.updateMode | default "Off" }}"
{{- end }}
